---
title: "My second post"
description: |
  Reactions to Miller (1965), Newell (1973), and Schacter et al. (1978)
author:
  - name: Wiston Rodriguez  
    url: 
    affiliation: The Graduate Center and Baruch College
    affiliation_url: https://www.gc.cuny.edu/Home
date: 08-27-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

## Reactions to readings 

I felt quite intimidated after reading the course readings for this week. It made me realize how little of a background I have in cognitive psychology. If I am being honest, I found it rather difficult to get through the readings. I found myself having to Google several terms that I stumbled across. The only background knowledge I have of cognitive psychology is from my introductory course that I took as an undergraduate, which was many years ago. I found the Miller (1956) particularly difficult to get through even though I realized by the end that I had already heard of the 'seven plus or minus two' rule. It was hard to follow the Miller (1956) article mainly because the structure of the article was different than what we typically read in I/O. For example, I did not understand why the article headings were structured the way that they were. In addition, most of my research within I/O does not involve topics in cognitive psychology. 

The article by Newell (1973) brought up an interesting point as it relates to binary oppositions. Newell (1973) argues that the field of psychology investigates phenomena through binary oppositions. This made me wonder if by engaging in these tactics (i.e., binary oppositions), are we potentially slowing down the speed in which our field advances? I had this thought primarily because of the examples provided in the binary oppositions. Specifically, the example of nature versus nurture was provided. From my understanding, in personality psychology there has been a debate on which exerts greater influence. However, early debates focused solely on which "side" presented a more valid argument. The field now has progressed more towards investigating the <i>interaction</i> between nature vs. nurture. 

The reason why I bring this up is because joining a doctoral program has challenged me to think in different ways. Instead of putting things into binary oppositions, I've learned to consider more the context in which things operate. For example, in I/O psychology we study organizational citizenship behaviors (OCBs), which are ultimately extra role behaviors that employees engage in that benefit the organization and/or its members. Counterproductive workplace behaviors (CWBs) on the other hand are behaviors that are carried out by employees with the intention to harm the organization and its members. As undergraduates we are programmed to think of these constructs as opposites, with OCBs regarded as pleasant behaviors and CWBs as unpleasant behaviors. However, I would like to pursue research that challenges these assumptions. I think it would be interesting to pursue research that shows how an employee who engages in too many OCBs could have unintended consequences for the organization, its members, and/or the individual 

I did find the Schacter et al. (1978) paper interesting since this was my first time reading about Semon's Theory of Memory. I found it interesting how Semon prioritized retrieval phenomena while his contemporaries did not. Retrieval as it relates to performance management in I/O is of extreme important. If managers are unable to successfully retrieve work related memories then chances are that they will not accurately be able to assess the performance of their subordinates. I think it would be of great value for me to continue learning more about memory in general because it relates to so many aspects within I/O that go beyond performance management. For example, understanding memory retrieval would also be beneficial as it relates to training. If trainees or even trainers are unable to recall information then it is likely that the training will be ineffective, resulting in financial costs for the organization.  
